mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 50020
spring:
    application:
        name: x-tool
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: root
        url: jdbc:mysql://localhost:3306/information_schema?serverTimezone=UTC
        username: root
    resources:
        static-locations: classpath:/static/
